### ISSUE TITLE
Demo test failing in real environment

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-incubator/cf-abacus#3]
Hi,
when trying to run the demo application, I get an exception as follows: 

```batch
npm run demo 192.168.204.16.xip.io 

> cf-abacus@0.0.1 demo /development/oss/cloudfoundry/cf-abacus
> bin/demo "192.168.204.16.xip.io"


> cf-abacus-demo-client@0.0.1 demo /development/oss/cloudfoundry/cf-abacus/node_modules/cf-abacus-demo-client
> mocha "192.168.204.16.xip.io"

Testing...


 cf-abacus-demo-client
       Submitting 10 GB, 1000 light API calls, 100 heavy API calls
       Submitting 10 GB, 1000 light API calls, 100 heavy API calls
       Submitting 10 GB, 1000 light API calls, 100 heavy API calls

       Waiting 1 second to make sure usage has been processed

       Retrieving usage report

{ organization_guid: 'a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27',
 start: 1435622400000,
 end: 1435708799999,
 id: 'k-a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27-t-0001435622400000',
 spaces: 
  [ { id: 'aaeae239-f3f8-483c-9dd0-de5d41c38b6a',
      consumers: 
       [ { id: 'all',
           services: 
            [ { id: 'storage',
                aggregated_usage: 
                 [ { unit: 'STORAGE_PER_MONTH', quantity: 1 },
                   { unit: 'THOUSAND_LIGHT_API_CALLS_PER_MONTH', quantity: 1 },
                   { unit: 'HEAVY_API_CALLS_PER_MONTH', quantity: 100 } ] } ] } ],
      services: 
       [ { id: 'storage',
           aggregated_usage: 
            [ { unit: 'STORAGE_PER_MONTH', quantity: 1 },
              { unit: 'THOUSAND_LIGHT_API_CALLS_PER_MONTH', quantity: 1 },
              { unit: 'HEAVY_API_CALLS_PER_MONTH', quantity: 100 } ] } ] } ],
 services: 
  [ { id: 'storage',
      aggregated_usage: 
       [ { unit: 'STORAGE_PER_MONTH', quantity: 1 },
         { unit: 'THOUSAND_LIGHT_API_CALLS_PER_MONTH', quantity: 1 },
         { unit: 'HEAVY_API_CALLS_PER_MONTH', quantity: 100 } ] } ] } 

   1) submits usage for storage service and verifies the submission using usage report


 0 passing (1s)
 1 failing

 1) cf-abacus-demo-client submits usage for storage service and verifies the submission using usage report:

     Uncaught AssertionError: expected { Object (organization_guid, spaces, ...) } to deeply equal { Object (organization_guid, services, ...) }
     + expected - actual

                "quantity": 1
                "unit": "STORAGE_PER_MONTH"
              }
              {
     -          "quantity": 1
     +          "quantity": 3
                "unit": "THOUSAND_LIGHT_API_CALLS_PER_MONTH"
              }
              {
     -          "quantity": 100
     +          "quantity": 300
                "unit": "HEAVY_API_CALLS_PER_MONTH"
              }
            ]
            "id": "storage"
                        "quantity": 1
                        "unit": "STORAGE_PER_MONTH"
                      }
                      {
     -                  "quantity": 1
     +                  "quantity": 3
                        "unit": "THOUSAND_LIGHT_API_CALLS_PER_MONTH"
                      }
                      {
     -                  "quantity": 100
     +                  "quantity": 300
                        "unit": "HEAVY_API_CALLS_PER_MONTH"
                      }
                    ]
                    "id": "storage"
                    "quantity": 1
                    "unit": "STORAGE_PER_MONTH"
                  }
                  {
     -              "quantity": 1
     +              "quantity": 3
                    "unit": "THOUSAND_LIGHT_API_CALLS_PER_MONTH"
                  }
                  {
     -              "quantity": 100
     +              "quantity": 300
                    "unit": "HEAVY_API_CALLS_PER_MONTH"
                  }
                ]
                "id": "storage"
     
     at _stream_readable.js:908:16




Run time 1510ms

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "demo" "192.168.204.16.xip.io"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! cf-abacus-demo-client@0.0.1 demo: `mocha "192.168.204.16.xip.io"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cf-abacus-demo-client@0.0.1 demo script 'mocha "192.168.204.16.xip.io"'.
npm ERR! This is most likely a problem with the cf-abacus-demo-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha "192.168.204.16.xip.io"
npm ERR! You can get their info via:
npm ERR!     npm owner ls cf-abacus-demo-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /development/oss/cloudfoundry/cf-abacus/node_modules/cf-abacus-demo-client/npm-debug.log

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "demo" "192.168.204.16.xip.io"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! cf-abacus@0.0.1 demo: `bin/demo "192.168.204.16.xip.io"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cf-abacus@0.0.1 demo script 'bin/demo "192.168.204.16.xip.io"'.
npm ERR! This is most likely a problem with the cf-abacus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bin/demo "192.168.204.16.xip.io"
npm ERR! You can get their info via:
npm ERR!     npm owner ls cf-abacus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /development/oss/cloudfoundry/cf-abacus/npm-debug.log 
```

**Comment by jsdelfino** [comment]
Does the same demo work for you outside of Cloud Foundry with npm start && npm run demo?

I'm thinking that this could be just a timing issue where the test client doesn't wait long enough to get the usage report. So if things run a little slower in your Cloud Foundry deployment for example, then the client may get the report a bit too early, before all the submitted usage has been metered.

You could try increasing the timeout in demo/client/test/test.js, on that line:
```javascript
setTimeout(() => get(done), 1000);
```
If that's indeed the issue, then that test client could be changed to loop on getting reports (for some reasonable max time) until it sees all the submitted usage.

I'll try in my environment as well with artificial delays in the metering to see if I get the same issue.

**Comment by jsdelfino** [comment]
I committed a change in 3f00944 to make the demo client retry until it gets the expected values, instead of getting a single usage report too early and failing to find the values it expects. See that commit for the details. Let me know if that fixes the problem you reported in this issue.

**Comment by hsiliev** [comment]
We have the same problem as @jhiemer. We increased the timeout to 200 000 and tried the tip of master branch on bosh-lite CF, AWS installed CF and standalone, but now we get:
```
  1) abacus-demo-client submits usage for a sample storage service and retrieves an aggregated usage report:
     Error: timeout of 202000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by jsdelfino** [comment]
You mentioned standalone too, did you mean that you're seeing the same problem with an npm start and npm run demo outside of CF?

This may not be a timeout issue. If one of the services fails to process the submitted usage for example then the test client will never get the expected report. Could you try the following steps:
```
export DEBUG=abacus-usage-*
npm start
npm run demo
```
and see if any of services (collector, meter, accumulator, aggregator) is reporting an error?

**Comment by hsiliev** [comment]
We successfully run the demo on Ubuntu (node: 0.12.7, npm: **2.11.3**) but on our Mac it still fails. Here is a gist with the npm/node versions and the logs: https://gist.github.com/hsiliev/75682df0e04d16f641fb

**Comment by jsdelfino** [comment]
This line in the logs you posted:
```
2015-08-11T13:17:43.183Z abacus-usage-accumulator 6767 Skipping duplicate usage { start: 1435629365220, end: 1435629465220, region: 'eu-gb', organization_guid: 'a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27', space_guid: 'aaeae239-f3f8-483c-9dd0-de5d41c38b6a', plan_id: 'plan_123', ...
```
shows that the Abacus usage accumulator service found a duplicate usage in the demo database (usage already reported for the exact same service instance and start and end times), so I'm thinking that your demo database may contain usage from a previous (potentially unsuccessful) run of the demo.

The sample database server app we include with the demo only stores the data in memory so you should be able to clean that duplicate usage by just restarting the apps.

Can you try the following steps?
```
cd <abacus top directory>
npm stop
npm start
npm run demo
```

**Comment by hsiliev** [comment]
Tried to stop/start and run the demo, but with no luck. We extracted the requests and executed them manually:
```
curl -i http://localhost:9080/v1/metering/services/storage/usage -H "Content-Type: application/json" -X POST -d '{
  "service_instances": [
    {
      "service_instance_id": "0b39fa70-a65f-4183-bae8-385633ca5c87",
      "usage": [
        {
          "start": 1435629365220,
          "end": 1435629465220,
          "region": "eu-gb",
          "organization_guid": "a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27",
          "space_guid": "aaeae239-f3f8-483c-9dd0-de5d41c38b6a",
          "plan_id": "plan_123",
          "resources": [
            {
              "unit": "BYTE",
              "quantity": 1073741824
            },
            {
              "unit": "LIGHT_API_CALL",
              "quantity": 1000
            },
            {
              "unit": "HEAVY_API_CALL",
              "quantity": 100
            }
          ]
        }
      ]
    }
  ]
}'
HTTP/1.1 201 Created
X-Powered-By: Express
Vary: X-HTTP-Method-Override, Accept-Encoding
X-Process-Id: 66444
X-Uptime: 3.682
X-Heap-Used: 34437160
X-Node-Version: v0.12.7
X-Instance-Id: 66444
X-Instance-Index: 0
Location: http://localhost:9080/v1/metering/services/storage/usage/t-0001439382903541-0-1-0-k-storage
Content-Type: application/json; charset=utf-8
Content-Length: 107
ETag: W/"6b-UYLwAfnaIhl61CKkS4Pc2w"
X-Response-Time: 268.475ms
Date: Wed, 12 Aug 2015 12:35:03 GMT
Connection: keep-alive

["http://localhost:9080/v1/metering/usage/t-0001439382903641-0-1-0-k-a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27"]
```

The reporting part however does not return anything:
```
curl http://localhost:9088/v1/organizations/a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27/usage/2015-6-30
  abacus-usage-reporting 66443 Retrieving aggregated usage for organization a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27 on 2015-6-30 +0ms
  abacus-usage-reporting 66443 Retrieving aggregated usage for k-a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27-t-0001435536000000 +2ms
  abacus-usage-reporting 66443 No existing aggregated usage +67ms
{"id":"a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27","services":[],"spaces":[]}
```
Here are the logs of abacus on [npm start](https://gist.github.com/hsiliev/0fbbdb5f1f5966bcdb30) and [demo run](https://gist.githubusercontent.com/hsiliev/acd1c60034f184f1994f/raw/ab9bf24b85b6f2900ae7006723ce7097c9c4978f/npm%2520run%2520demo) with lots of debug info. 

What are we doing wrong?

**Comment by hsiliev** [comment]
Found the reason for the failure: the month and date have to include a leading zero (two digits)

Created pull request https://github.com/cloudfoundry-incubator/cf-abacus/pull/9

**Comment by jsdelfino** [comment]
Thanks for the fix!
